name: Build and Publish SQLite DB

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 curl unzip xz-utils

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          rm -rf aws awscliv2.zip

      - name: Build database
        run: |
          chmod +x populate.sh
          ./populate.sh \
            --driver sqlite \
            --db-path location.db

      - name: Generate metadata
        run: |
          SHA=$(sha256sum location.db | awk '{print $1}')
          XZ_SHA=$(sha256sum location.db.xz | awk '{print $1}')
          SIZE=$(stat -c%s location.db)
          XZ_SIZE=$(stat -c%s location.db.xz)
          ROWS_GEONAMES_CITIES=$(sqlite3 location.db "SELECT COUNT(*) FROM geonames_cities;")
          ROWS_GEONAMES_STATES=$(sqlite3 location.db "SELECT COUNT(*) FROM geonames_states;")
          ROWS_GEONAMES_COUNTRIES=$(sqlite3 location.db "SELECT COUNT(*) FROM geonames_countries;")
          ROWS_GEONAMES_TRIGRAMS=$(sqlite3 location.db "SELECT COUNT(*) FROM geonames_trigrams;")

          cat > location.json <<EOF
          {
            "version":"$(date -u +%Y-%m-%d)",
            "updated":"$(date -u +%FT%TZ)",
            "sha256":"$SHA",
            "size":$SIZE,
            "xz": {
              "sha256":"$XZ_SHA",
              "size":$XZ_SIZE,
              "url":"https://locationdb.utkarshchourasia.in/location.db.xz"
            },
            "rows":{
              "geonames_cities":$ROWS_GEONAMES_CITIES,
              "geonames_states":$ROWS_GEONAMES_STATES,
              "geonames_countries":$ROWS_GEONAMES_COUNTRIES,
              "geonames_trigrams":$ROWS_GEONAMES_TRIGRAMS
            }
          }
          EOF

      - name: Upload to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
        run: |
          aws s3 cp location.db    s3://locationdb/location.db
          aws s3 cp location.db.xz s3://locationdb/location.db.xz
          aws s3 cp location.json  s3://locationdb/location.json